require 'rubygems'
require 'json'
require 'net/scp'
require 'fileutils'
require 'tempfile'
require 'ostruct'
require "#{File.dirname(__FILE__)}/thimbl/base"
require "#{File.dirname(__FILE__)}/thimbl/command"
require "#{File.dirname(__FILE__)}/thimbl/finger"
require "#{File.dirname(__FILE__)}/thimbl/utils"
